# Generated by Django 3.2.7 on 2021-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_item_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='product_cart', to='main.ProductOrder'),
        ),
    ]
