# Generated by Django 3.2.7 on 2021-09-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
